### ISSUE TITLE
Can't connect a trailer to a storage trailer (1.12.2)

### ISSUE THREAD

**Issue by coolmantwenty20** [MrCrayfish/MrCrayfishVehicleMod#177] opened 2020-01-10 05:31 UTC
I'm unable to connect a trailer to a storage trailer, whether it be a fluid trailer, a vehicle trailer, a fertilizer, or a seeder. I can't find anything anywhere on how to fix this. I've tried clicking all on top of, on the side of, on the hitch, and underneath the storage trailer with another trailer, but I can't seem to find the sweet spot. I've tried attaching things to the storage trailer while it is connected to a vehicle, and while it isn't connected to a vehicle. Maybe you could add a hotkey for this, or make it so you have to do a certain button combo to open the chest itself.
If possible, in the short run, is there any sort of command to hitch the trailers that way?
Thanks in advance.

**Comment by MrCrayfish** [comment] 2020-01-11 03:04
Duplicate of https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/154

**Closed by MrCrayfish** 2020-01-11 03:04 UTC
