### ISSUE TITLE
[1.12.2] Exception in server tick loop

### ISSUE THREAD

**Issue by MusicMaestro123** [MrCrayfish/MrCrayfishVehicleMod#233] opened 2020-03-29 17:23 UTC
I had this crash after updating to 0.43.5: [Click here to view crash report!](https://pastebin.com/Jv9rjqMP)

**Comment by MrCrayfish** [comment] 2020-03-30 06:04
Duplicate of https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/232

**Closed by MrCrayfish** 2020-03-30 06:04 UTC
