### ISSUE TITLE
The vehicle got stuck in hands then when try to execute /kill command game crashes

### ISSUE THREAD

**Issue by saharking1298** [MrCrayfish/MrCrayfishVehicleMod#169] opened 2019-11-23 15:40 UTC

**Comment by D-H-U** [comment] 2019-12-30 14:36
Do you only have vehicle mod installed? Test he alone and try reproduce this problem again.

I also advise giving a more detailed description of the problem, to help the developer figure out the problem (if it occurs with the mod).

Some things like:
- **Mod Version**
- **Forge Version** (that you are using)
- **Minecraft Version**
- **Log.txt** (if it crashes and there is one)

It will help a lot!

**Comment by MrCrayfish** [comment] 2020-01-02 06:42
"vehicle got stuck in hands" You picked up the vehicle. It's a feature in the Vehicle Mod. Crouch and right click the ground to place it back down. In terms of it crashing, I will look into the issue.

**Comment by MrCrayfish** [comment] 2020-03-18 08:53
Closing because no crash log is provided. Open a new issue if you have the crash log

**Closed by MrCrayfish** 2020-03-18 08:53 UTC
