### ISSUE TITLE
Cant attach anything to storage trailer's hitch 0.41.1

### ISSUE THREAD

**Issue by Pleune** [MrCrayfish/MrCrayfishVehicleMod#162] opened 2019-10-21 19:45 UTC
When trying to attach any trailer onto the back of a storage trailer, it instead opens the storage trailer's inventory. I can't seem to find any way around this, when shift clicking with carrying turned off.

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment] 2019-11-03 13:20
you have to click further than the hook, towards the chest and it works. I had the same problem then figured it out!

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment] 2020-01-09 01:09
@Pleune you have to click further than the hook, towards the chest and it works. I had the same problem then figured it out!

**Comment by MrCrayfish** [comment] 2020-01-11 03:04
Duplicate of https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/154

**Closed by MrCrayfish** 2020-01-11 03:04 UTC
