### ISSUE TITLE
Connecting Storage Trailers Together in the latest version of 1.12.2 (Vehicle Mod)-MrCrayFish

### ISSUE THREAD

**Issue by ItzTwoost** [MrCrayfish/MrCrayfishVehicleMod#168] opened 2019-11-22 21:53 UTC
In the latest version I can't connect storage trailers to each other and I have tried many times. 
If you know why please tell me, I thinks it's a bug but probs not.
I don't know how to show that it isn't working.
I tried filling the chests, repainting the trailers different colors, restarting minecraft, watching MrCrayFish's videos and still can't.

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment] 2020-01-09 01:08
@ItzTwoost you have to tap more to the center of the chest on the trailer

**Comment by ItzTwoost** [comment] 2020-01-09 01:47
That doesn't make that much sense because you should need to aim at the trailer hitch, right?

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment] 2020-01-09 12:10
@ItzTwoost it works. I dont know why that is, but it works.

**Comment by MrCrayfish** [comment] 2020-01-11 03:04
Duplicate of https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/154

**Closed by MrCrayfish** 2020-01-11 03:04 UTC
