### ISSUE TITLE
Crashes upon world loading [1.12.2]

### ISSUE THREAD

**Issue by erinhenry** [MrCrayfish/MrCrayfishVehicleMod#235] opened 2020-03-30 03:51 UTC
I've mixed and matched my mods with it, and then even tried it on its own, but nothing seems to change. It loads the main menu just fine, but once I either try to create a new world or load a previous one, it crashes. Crash linked here (Crash from it being loaded on its own) > https://pastebin.com/iNFr9pLD

I read through some of the closed versions of the similar issues, and took account of the fixes you suggested (using recommended forge, having too many mods, etc.) but sadly, nothing is working.

Just hope to be able to use the mod, loving the devices and furniture ones !

**Comment by MrCrayfish** [comment] 2020-03-30 06:04
Duplicate of https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/232

**Closed by MrCrayfish** 2020-03-30 06:04 UTC
