### ISSUE TITLE
Can't open crate in Survival mode

### ISSUE THREAD

**Issue by MancV21** [MrCrayfish/MrCrayfishVehicleMod#102] opened 2019-02-28 17:36 UTC
Hi. I've just added the latest version of the mod and built a Sofacopter. It dropped the crate which I picked up, took outside to an empty field and placed on the floor. I tried left and right clicking, but nothing happened. I then saw a post on here that you need a wrench to open it, so I created a wrench, then left and right clicked the crate but still nothing. All it does is generate the particles as though it's going to break, but never does. Am I missing something?

MC version 1.12.2
Obsfucate 0.2.6
Vehicle Mod 0.36.1

Here's a video showing what I'm doing. - https://www.youtube.com/watch?v=qN40F_fYB8o&feature=youtu.be

Thanks.

EDIT - Don't know if this helps but if I switch to CREATIVE mode and search for a crate with the SofaCopter in it and put it in my inv, then switch back to SURVIVAL and right-click with the wrench, it works. So it's something to do with the crate the workstation is dropping in SURVIVAL mode. Also does this for every vehicle, so it's not jus the SofaCopter :)

**Comment by Shuazijun** [comment] 2019-04-07 08:08
Please try to bring enough material to generate crates on the worker in lifestyle instead of creating patterns. It occasionally generates this bug on the server.

**Comment by pjcarmen** [comment] 2019-04-09 17:26
I have had this happen as well. I crafted the Sofacopter, the crate popped out and when I placed it on the ground, it did not have the Sofacopter "lore" tooltip and I was unable to open it. I crafted a second one and it had the tooltip and of course, it was able to be opened.

**Comment by MrCrayfish** [comment] 2020-03-17 13:03
Closing this as I can't reproduce. Open a new issue if this is still present in newer versions

**Closed** 2020-03-17 13:03 UTC

**Comment by andrewminer** [comment] 2020-06-25 13:59
For what it's worth, I've just experienced this with version 0.43.0 as part of the [Ad Astra](https://github.com/andrewminer/ad-astra) modpack.
