### ISSUE TITLE
Storage trailer wont connect to the back of another storage trailer

### ISSUE THREAD

**Issue by guardian606** [MrCrayfish/MrCrayfishVehicleMod#154] opened 2019-08-29 13:31 UTC
im wanting to add this mod to my modpack and i wanted to make sure every thing worked before i put it in and i cant seem to get the storage trailers to connect to one another 

here is a video of me trying to get it to connect

https://youtu.be/0HRF_1vCAnQ

**Comment by guardian606** [comment] 2019-08-29 13:37
update i went down a version and its works so did something change from the old one to the new one ?

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment] 2019-10-19 15:06
click in the center with the trailer attached

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment] 2020-01-09 01:09
@guardian606 you have to click further than the hook, towards the chest and it works. I had the same problem then figured it out!

**Comment by Kathartrix** [comment] 2020-01-14 04:28
Referencing #162 as well.
This problem persists into 0.41.2 with forge versions 30.0.32 & 30.0.39. No amount of clicking on or around the trailer causes any trailer to link to the back of the Storage trailer. The player arm will swing like it does when connecting trailers to the back of the Tractor or ATV.

-As an aside Chest is missing from the Storage trailer and is also not accessible as an inventory.
![During_Connecting_To_TrailerHitch](https://user-images.githubusercontent.com/38929944/72314195-ea5b5780-365b-11ea-8fac-e4dce5b8d431.png)
![After_Connecting_To_TrailerHitch](https://user-images.githubusercontent.com/38929944/72314193-ea5b5780-365b-11ea-87db-4abb65f940d4.png)

![During_Connecting_To_TractorHitch](https://user-images.githubusercontent.com/38929944/72314194-ea5b5780-365b-11ea-9c53-f51a81f1da1e.png)
![After_Connecting_To_TractorHitch](https://user-images.githubusercontent.com/38929944/72314196-eaf3ee00-365b-11ea-94e7-66c2e609743e.png)

**Comment by Synthlatren** [comment] 2020-03-20 23:12
I've been having the same issue as well (in MC 1.12.2) and I was a little disappointed when this wasn't fixed in the 0.43.4 version released today. So I did some investigation work comparing versions and looking through their code, and I hope you find what I found helpful.

In version 0.41.0 and before, a player could connect any trailer to the storage trailer without an issue. Then in version 0.41.1 and every successive version following, the issue is present. When I dove into the code of these versions and compared the two, I believe the issue appeared when there was a significant change to _EntitySorageTrailer.class_ and _EntityTrailer.class_ files and how they interacted with the raytracing of the player interaction (?) (I'm only guessing though because I only started to learn how to read code and write in C a few months ago and your mod is way more advanced than what I'm doing). I've also attached a text file that contains a timeline of the issue and your changes to your mod.

[mrcrayfish notes - chest trailer.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4362065/mrcrayfish.notes.-.chest.trailer.txt)

**Comment by MrCrayfish** [comment] 2020-03-21 04:34
Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/7ab005a268b2ba81042bce3df16411d27749e968

**Closed by MrCrayfish** 2020-03-21 04:34 UTC

**Comment by SpeedDemonBlue** [comment] 2021-08-02 18:42
> click in the center with the trailer attached

so I've tried this many times, even in different places on the trailer and all that happens is the storage trailer opening
![2021-08-02_14 43 14](https://user-images.githubusercontent.com/84389221/127908647-4c4ef8d4-be38-479c-a2de-599f4c0ce0f6.png)

I've looked through the MrCrayfish working storage trailer video and found nothing but him doing the same thing I've been doing for the past HOUR and yet it still doesn't work.  I've looked through this entire page and other pages in github about this issue and the answers are the same, "click in the center of the trailer attached."  Could you please add detail and a screenshot of where the "center" is!?
