### ISSUE TITLE
I found a bug/glitch

### ISSUE THREAD

**Issue by Zjories** [MrCrayfish/MrCrayfishVehicleMod#224] opened 2020-03-20 20:36 UTC
so i found this bug/glitch where you can see through wals with a Fluid Extractor.
[MRcrayfish mod bug.zip](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4361711/MRcrayfish.mod.bug.zip)

**Comment by MrCrayfish** [comment] 2020-03-21 04:35
Duplicate of https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/198

**Closed by MrCrayfish** 2020-03-21 04:35 UTC
